### ISSUE TITLE
[Vue warn]: Error in render: "RangeError: Maximum call stack size exceeded" 

### ISSUE THREAD

**Issue by yiliang114** [yiliang114/yiliang114.github.io#56]

**Comment by yiliang114** [comment]
![Uploading image.png…]()

**Comment by yiliang114** [comment]
#https://github.com/vuejs/vuepress/issues/2656

**Comment by yiliang114** [comment]
在 `package.json` 里面 `dependencies` 加上"vue-router": "3.4.5"， yarn, cnpm 安装依赖比较蛋疼的是，npm run dev 还会出现这个问题，但是 build 不会。 后面换用 npm i 安装依赖之后就可以了

**Comment by johanazhu** [comment]
良辰在此谢过
